import 'package:flutter/material.dart';

import '../models/fermentation_project.dart';
import '../services/fermenter_controller.dart';
import '../utils/format.dart';
import '../widgets/feature_row.dart';
import '../widgets/status_chip.dart';
import 'new_project_page.dart';
import 'onboarding_page.dart';
import 'project_detail_page.dart';

/// 无硬件阶段统一口径的说明，欢迎页与列表页提示条共用。
const String _simulationNote = 'Simulation mode: readings are generated by the '
    'built-in simulator until the ESP32 hardware is connected.';

class HomePage extends StatefulWidget {
  const HomePage({super.key, required this.controller});

  final FermenterController controller;

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool _loadingSample = false;

  FermenterController get data => widget.controller;

  void _message(String text) {
    if (mounted) {
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text(text)));
    }
  }

  Future<void> _openNewProject() async {
    final created = await Navigator.of(context).push<bool>(
      MaterialPageRoute(builder: (_) => NewProjectPage(controller: data)),
    );
    if (created == true && mounted) _message('Batch started.');
  }

  /// 重播新手引导（首页右上角入口），不写引导标记。
  Future<void> _replayOnboarding() async {
    await Navigator.of(context).push<void>(
      MaterialPageRoute(
        builder: (routeContext) => OnboardingPage(
          isReplay: true,
          onDone: () => Navigator.of(routeContext).pop(),
        ),
      ),
    );
  }

  /// 生成一个跑完整周期的演示批次，并直接打开它，方便一次性检查
  /// 曲线、收获告警、统计与导出在无硬件情况下的表现。
  Future<void> _loadSampleData() async {
    setState(() => _loadingSample = true);
    int? id;
    try {
      id = await data.loadSampleBatch();
    } catch (_) {
      id = null;
    }
    if (!mounted) return;
    setState(() => _loadingSample = false);
    if (id == null) {
      _message('Could not load the sample data.');
      return;
    }
    _message('Sample data loaded.');
    final projectId = id;
    await Navigator.of(context).push<void>(
      MaterialPageRoute(
          builder: (_) =>
              ProjectDetailPage(controller: data, projectId: projectId)),
    );
    if (mounted) await data.refresh();
  }

  Future<void> _openProject(FermentationProject project) async {
    await data.selectProject(project.id);
    if (!mounted) return;
    await Navigator.of(context).push<void>(
      MaterialPageRoute(
          builder: (_) => ProjectDetailPage(controller: data, projectId: project.id)),
    );
    if (mounted) await data.refresh();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: data,
      builder: (context, _) => Scaffold(
        appBar: AppBar(
          title: const Text('Fermenter'),
          actions: [
            IconButton(
                onPressed: _replayOnboarding,
                tooltip: 'How it works',
                icon: const Icon(Icons.help_outline)),
            IconButton(
                onPressed: data.loading ? null : data.refresh,
                tooltip: 'Refresh',
                icon: const Icon(Icons.refresh)),
          ],
        ),
        // 欢迎页自带醒目的主按钮，没有批次时不再重复挂一个 FAB。
        floatingActionButton: data.projects.isEmpty
            ? null
            : FloatingActionButton.extended(
                onPressed: _openNewProject,
                icon: const Icon(Icons.add),
                label: const Text('New batch'),
              ),
        body: SafeArea(
          top: false,
          child: Center(
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 880),
              child: Column(
                children: [
                  if (data.loading)
                    const LinearProgressIndicator(minHeight: 2),
                  Expanded(
                    child: data.error != null
                        ? _errorView()
                        : RefreshIndicator(
                            onRefresh: data.refresh,
                            child: data.projects.isEmpty
                                ? _welcomeView()
                                : _projectList(),
                          ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _errorView() => Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(mainAxisSize: MainAxisSize.min, children: [
            const Icon(Icons.storage_outlined, size: 40),
            const SizedBox(height: 12),
            Text(data.error!),
            TextButton(onPressed: data.refresh, child: const Text('Retry')),
          ]),
        ),
      );

  // -- 欢迎页（还没有任何批次时）--

  Widget _welcomeView() => ListView(
        physics: const AlwaysScrollableScrollPhysics(),
        padding: const EdgeInsets.fromLTRB(24, 16, 24, 32),
        children: [
          _heroBanner(),
          const SizedBox(height: 20),
          FilledButton.icon(
            onPressed: _openNewProject,
            icon: const Icon(Icons.add),
            label: const Text('Create your first batch'),
            style: FilledButton.styleFrom(minimumSize: const Size.fromHeight(50)),
          ),
          const SizedBox(height: 10),
          OutlinedButton.icon(
            onPressed: _loadingSample ? null : _loadSampleData,
            icon: _loadingSample
                ? const SizedBox(
                    width: 16,
                    height: 16,
                    child: CircularProgressIndicator(strokeWidth: 2))
                : const Icon(Icons.auto_awesome, size: 18),
            label: Text(
                _loadingSample ? 'Generating sample data…' : 'Load sample data'),
            style: OutlinedButton.styleFrom(minimumSize: const Size.fromHeight(50)),
          ),
          const SizedBox(height: 12),
          Text(
            _simulationNote,
            textAlign: TextAlign.center,
            style: TextStyle(
                fontSize: 11.5,
                height: 1.3,
                color: Theme.of(context).colorScheme.onSurfaceVariant),
          ),
          const SizedBox(height: 28),
          _sectionTitle('What makes it different'),
          const SizedBox(height: 10),
          _harvestHighlight(),
          const SizedBox(height: 26),
          _sectionTitle('What it records'),
          const SizedBox(height: 4),
          const FeatureRow(
            icon: Icons.bubble_chart_outlined,
            title: 'Turbidity (OD600)',
            body: 'How cloudy the culture is. Growth pushes it up, lysis pulls '
                'it down — that drop is the harvest signal.',
            color: Colors.teal,
          ),
          const FeatureRow(
            icon: Icons.thermostat_outlined,
            title: 'Temperature',
            body: 'Ramps from room temperature to your target and holds it, '
                'with the heater and stirrer under your control.',
            color: Colors.deepOrange,
          ),
          const FeatureRow(
            icon: Icons.science_outlined,
            title: 'pH',
            body: 'Tracks the buffer drift: a slow dip while the cells grow, '
                'a small recovery once they start to lyse.',
            color: Colors.indigo,
          ),
          const SizedBox(height: 26),
          _sectionTitle('How it works'),
          const SizedBox(height: 10),
          _stepRow(1, 'Create a batch',
              'Name it, set the target temperature and how fast simulated time runs.'),
          _stepRow(2, 'Watch the live curves',
              'Every reading is stored and plotted, so the trend is visible at a glance.'),
          _stepRow(3, 'Harvest on signal',
              'When turbidity keeps falling from its peak, the app tells you it is time.'),
        ],
      );

  Widget _heroBanner() {
    final scheme = Theme.of(context).colorScheme;
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [scheme.primaryContainer, scheme.surface],
        ),
        borderRadius: BorderRadius.circular(20),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration:
                    BoxDecoration(color: scheme.primary, shape: BoxShape.circle),
                child: Icon(Icons.biotech_rounded,
                    size: 26, color: scheme.onPrimary),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  'iGEM Fermenter',
                  style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                      fontWeight: FontWeight.bold,
                      color: scheme.onPrimaryContainer),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            'Follow the culture from inoculation to harvest, and stop guessing '
            'when the protein is ready.',
            style: TextStyle(
                fontSize: 14.5, height: 1.35, color: scheme.onSurfaceVariant),
          ),
        ],
      ),
    );
  }

  Widget _harvestHighlight() {
    final scheme = Theme.of(context).colorScheme;
    return Card(
      margin: EdgeInsets.zero,
      color: scheme.primaryContainer,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(Icons.notifications_active_rounded,
                    color: scheme.onPrimaryContainer),
                const SizedBox(width: 8),
                Expanded(
                  child: Text('Harvest detection',
                      style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                          color: scheme.onPrimaryContainer)),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Text(
              'In the two-phase model the turbidity climbs while the cells '
              'grow, plateaus, then falls fast when they lyse. The app watches '
              'for that sustained fall and flags the harvest moment for you.',
              style: TextStyle(
                  fontSize: 13, height: 1.35, color: scheme.onPrimaryContainer),
            ),
          ],
        ),
      ),
    );
  }

  Widget _sectionTitle(String text) => Text(
        text,
        style: Theme.of(context)
            .textTheme
            .titleSmall
            ?.copyWith(fontWeight: FontWeight.bold),
      );

  Widget _stepRow(int index, String title, String body) {
    final scheme = Theme.of(context).colorScheme;
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 26,
            height: 26,
            alignment: Alignment.center,
            decoration: BoxDecoration(color: scheme.primary, shape: BoxShape.circle),
            child: Text('$index',
                style: TextStyle(
                    fontSize: 13,
                    fontWeight: FontWeight.bold,
                    color: scheme.onPrimary)),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title,
                    style: const TextStyle(
                        fontSize: 14, fontWeight: FontWeight.w600)),
                const SizedBox(height: 2),
                Text(body,
                    style: TextStyle(
                        fontSize: 12.5,
                        height: 1.35,
                        color: scheme.onSurfaceVariant)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _projectList() => ListView(
        physics: const AlwaysScrollableScrollPhysics(),
        padding: const EdgeInsets.fromLTRB(20, 12, 20, 96),
        children: [
          _sampleNote(),
          const SizedBox(height: 12),
          for (final project in data.projects) ...[
            _projectCard(project),
            const SizedBox(height: 10),
          ],
        ],
      );

  Widget _projectCard(FermentationProject project) {
    final scheme = Theme.of(context).colorScheme;
    return Card(
      margin: EdgeInsets.zero,
      child: InkWell(
        borderRadius: BorderRadius.circular(12),
        onTap: () => _openProject(project),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Expanded(
                    child: Text(
                      project.name,
                      style: const TextStyle(
                          fontSize: 16, fontWeight: FontWeight.bold),
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                  StatusChip(status: project.status),
                ],
              ),
              if (project.strain != null && project.strain!.isNotEmpty) ...[
                const SizedBox(height: 4),
                Text(project.strain!,
                    style: TextStyle(
                        fontSize: 12, color: scheme.onSurfaceVariant)),
              ],
              const SizedBox(height: 12),
              // 用 Wrap 而不是 Row：窄屏/大字号下三个指标会换行而不是溢出。
              Wrap(
                spacing: 16,
                runSpacing: 6,
                children: [
                  _miniMetric('Temp',
                      '${project.lastTemperatureC == null ? '—' : number(project.lastTemperatureC!)} °C'),
                  _miniMetric('pH',
                      project.lastPh == null ? '—' : number(project.lastPh!)),
                  _miniMetric('OD600',
                      project.lastOd == null ? '—' : number(project.lastOd!, 3)),
                ],
              ),
              const SizedBox(height: 10),
              Row(
                children: [
                  Icon(Icons.timelapse_rounded,
                      size: 14, color: scheme.onSurfaceVariant),
                  const SizedBox(width: 4),
                  Text(simDurationLabel(project.simSeconds),
                      style: TextStyle(
                          fontSize: 12, color: scheme.onSurfaceVariant)),
                  const Spacer(),
                  Icon(Icons.chevron_right, color: scheme.onSurfaceVariant),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _miniMetric(String label, String value) => Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label,
              style: TextStyle(
                  fontSize: 11, color: Theme.of(context).colorScheme.onSurfaceVariant)),
          Text(value,
              style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14)),
        ],
      );

  Widget _sampleNote() =>
      _SimulationNote(busy: _loadingSample, onLoadSample: _loadSampleData);
}

/// 无硬件阶段的提示条 + 「载入样例数据」入口。
class _SimulationNote extends StatelessWidget {
  const _SimulationNote({required this.busy, required this.onLoadSample});

  final bool busy;
  final VoidCallback onLoadSample;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.fromLTRB(12, 12, 12, 4),
      decoration: BoxDecoration(
        color: scheme.secondaryContainer,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(Icons.memory_outlined,
                  size: 20, color: scheme.onSecondaryContainer),
              const SizedBox(width: 10),
              Expanded(
                child: Text(
                  _simulationNote,
                  style: TextStyle(
                      fontSize: 12.5, color: scheme.onSecondaryContainer),
                ),
              ),
            ],
          ),
          Align(
            alignment: Alignment.centerRight,
            child: TextButton.icon(
              onPressed: busy ? null : onLoadSample,
              icon: busy
                  ? const SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2))
                  : const Icon(Icons.auto_awesome, size: 18),
              label: Text(
                  busy ? 'Generating sample data…' : 'Load sample data'),
            ),
          ),
        ],
      ),
    );
  }
}